### ISSUE TITLE
only prints first page in chromium and icecat (firefox)

### ISSUE THREAD

**Issue by jolly-jump** [ether/ep_print#10]
Hi, 

I have the following plugins installed:

ETHERPAD_PLUGINS="ep_headings2 ep_comments_page ep_embedded_hyperlinks2 ep_ldapauth ep_author_neat ep_readonly_guest ep_cursortrace ep_copy_paste_images ep_adminpads2 ep_whiteboard ep_who_did_what ep_dis\
able_reset_authorship_colours ep_print"

and libreoffice, tidy and make are installed.

the print function only prints the first page and two more empty pages in icecat (firefox 78.3.0esr (64-bit)) and only the first page in chromium (Version 87.0.4280.88 (Offizieller Build) Arch Linux (64-Bit))

I guess this is not what the plugin should do.

Any help appreciated! Thanks

**Comment by JohnMcLear** [comment]
What happens if the other plugins are not installed?  Does this plugin function as intended?

**Comment by jolly-jump** [comment]
Well, I uninstalled all other plugins: same result. Prints only the first page.

I am not sure what you mean by "intended"? The website says "prints pagebreaks" which probably means, it does a page break if I mark a page break somewhere - but I don't know how.
So I have not manually marked a page break and *hoped* ep_print would then print several pages if the document does not fit on one page. 

In firefox it does somehow calculate the number of pages (probably) right, but prints the second and third empty (except the headers which are added by firefox I guess).

In Chromium only the first page is rendered and I am able to print only the first there.

**Comment by JohnMcLear** [comment]
Just an update on this, I started working on it and it's really broken.  Will fix ASAP

**Comment by JohnMcLear** [comment]
If you try the latest does it work?

**Comment by JohnMcLear** [comment]
Fixed :)

**Comment by jolly-jump** [comment]
I'll test it as well. Thanks for the superquick response!

**Comment by jolly-jump** [comment]
Works for me as well.
